FROM ghcr.io/astral-sh/uv:0.7.15 AS uv
FROM python:3.12-slim

WORKDIR /services

# Enable bytecode compilation, to improve cold-start performance.
ENV UV_COMPILE_BYTECODE=1

# Disable installer metadata, to create a deterministic layer.
ENV UV_NO_INSTALLER_METADATA=1

# Enable copy mode to support bind mount caching.
ENV UV_LINK_MODE=copy

# Install common dependencies
COPY uv.lock pyproject.toml ./

# Install UV
COPY --from=uv /uv /bin/uv
RUN uv sync --frozen

# Set Python path
ENV PYTHONPATH=/services

# Copy services code
COPY services/ ./
COPY src/services/google_authentication.py ./src/services/
COPY src/services/google_calendar.py ./src/services/
COPY src/models/io_models.py ./models/

ENTRYPOINT ["uv", "run", "python", "insert_events.py", "--host", "0.0.0.0", "--port", "8080"]